const marathons = [
  {
    id: 'berlin',
    name: 'Berlin Marathon',
    location: 'Berlin, Germany',
    distanceKm: 42.195,
    elevationGain: 72,
    elevationLoss: 70,
    difficulty: 0.95,
    surface: 'Road',
    description: 'One of the fastest marathon courses in the world. Almost completely flat with wide streets.',
    color: '#E3000F',
    country: 'DE',
  },
  {
    id: 'boston',
    name: 'Boston Marathon',
    location: 'Boston, USA',
    distanceKm: 42.195,
    elevationGain: 243,
    elevationLoss: 294,
    difficulty: 1.15,
    surface: 'Road',
    description: 'Net downhill but features Heartbreak Hill at mile 20. Rolling hills throughout.',
    color: '#004B87',
    country: 'US',
  },
  {
    id: 'london',
    name: 'London Marathon',
    location: 'London, UK',
    distanceKm: 42.195,
    elevationGain: 115,
    elevationLoss: 118,
    difficulty: 1.00,
    surface: 'Road',
    description: 'Flat and fast course along the River Thames. Many iconic landmarks.',
    color: '#CF142B',
    country: 'GB',
  },
  {
    id: 'chicago',
    name: 'Chicago Marathon',
    location: 'Chicago, USA',
    distanceKm: 42.195,
    elevationGain: 56,
    elevationLoss: 53,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Very flat course through 29 neighborhoods. Excellent for fast times.',
    color: '#009CDE',
    country: 'US',
  },
  {
    id: 'nyc',
    name: 'NYC Marathon',
    location: 'New York, USA',
    distanceKm: 42.195,
    elevationGain: 312,
    elevationLoss: 315,
    difficulty: 1.20,
    surface: 'Road',
    description: 'Five-borough tour with multiple bridges. Verrazzano bridge start is iconic.',
    color: '#FF6B35',
    country: 'US',
  },
  {
    id: 'tokyo',
    name: 'Tokyo Marathon',
    location: 'Tokyo, Japan',
    distanceKm: 42.195,
    elevationGain: 48,
    elevationLoss: 45,
    difficulty: 0.92,
    surface: 'Road',
    description: 'Almost pancake flat. Excellent organization and crowd support.',
    color: '#BC002D',
    country: 'JP',
  },
  {
    id: 'bigsur',
    name: 'Big Sur Marathon',
    location: 'Big Sur, USA',
    distanceKm: 42.195,
    elevationGain: 430,
    elevationLoss: 415,
    difficulty: 1.35,
    surface: 'Road',
    description: 'Stunning coastal views but extremely challenging. Hurricane Point at mile 11.',
    color: '#2E8B57',
    country: 'US',
  },
  {
    id: 'paris',
    name: 'Paris Marathon',
    location: 'Paris, France',
    distanceKm: 42.195,
    elevationGain: 145,
    elevationLoss: 142,
    difficulty: 1.02,
    surface: 'Road',
    description: 'Mild rolling hills through the streets of Paris. Starts on Champs-Élysées.',
    color: '#002395',
    country: 'FR',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam Marathon',
    location: 'Amsterdam, Netherlands',
    distanceKm: 42.195,
    elevationGain: 38,
    elevationLoss: 36,
    difficulty: 0.90,
    surface: 'Road',
    description: 'Extremely flat course. Perfect for a personal best.',
    color: '#FF6600',
    country: 'NL',
  },
  {
    id: 'rome',
    name: 'Rome Marathon',
    location: 'Rome, Italy',
    distanceKm: 42.195,
    elevationGain: 180,
    elevationLoss: 178,
    difficulty: 1.08,
    surface: 'Road',
    description: 'Cobblestone sections and rolling hills. Historic landmarks throughout.',
    color: '#E32636',
    country: 'IT',
  },
  {
    id: 'valencia',
    name: 'Valencia Marathon',
    location: 'Valencia, Spain',
    distanceKm: 42.195,
    elevationGain: 30,
    elevationLoss: 28,
    difficulty: 0.88,
    surface: 'Road',
    description: 'Among the flattest marathons in the world. Top choice for record attempts.',
    color: '#FFA500',
    country: 'ES',
  },
  {
    id: 'prague',
    name: 'Prague Marathon',
    location: 'Prague, Czech Republic',
    distanceKm: 42.195,
    elevationGain: 95,
    elevationLoss: 92,
    difficulty: 0.97,
    surface: 'Road',
    description: 'Mostly flat with some cobblestone. Scenic route through Old Town.',
    color: '#E30A17',
    country: 'CZ',
  },
  {
    id: 'marina-bay',
    name: 'Marina Bay Marathon',
    location: 'Singapore',
    distanceKm: 42.195,
    elevationGain: 35,
    elevationLoss: 33,
    difficulty: 0.89,
    surface: 'Road',
    description: 'Flat coastal route. Warm and humid conditions add challenge.',
    color: '#EF2B2D',
    country: 'SG',
  },
  {
    id: 'vienna',
    name: 'Vienna Marathon',
    location: 'Vienna, Austria',
    distanceKm: 42.195,
    elevationGain: 68,
    elevationLoss: 65,
    difficulty: 0.94,
    surface: 'Road',
    description: 'Flat and fast through imperial Vienna. Ends at the Hofburg Palace.',
    color: '#C8102E',
    country: 'AT',
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen Marathon',
    location: 'Copenhagen, Denmark',
    distanceKm: 42.195,
    elevationGain: 42,
    elevationLoss: 40,
    difficulty: 0.91,
    surface: 'Road',
    description: 'Flat city course through the Danish capital. Great for beginners.',
    color: '#C60C30',
    country: 'DK',
  },
  {
    id: 'geneva',
    name: 'Geneva Marathon',
    location: 'Geneva, Switzerland',
    distanceKm: 42.195,
    elevationGain: 88,
    elevationLoss: 85,
    difficulty: 0.96,
    surface: 'Road',
    description: 'Flat lakeside course with views of Mont Blanc and Lake Geneva.',
    color: '#E32636',
    country: 'CH',
  },
  {
    id: 'barcelona',
    name: 'Barcelona Marathon',
    location: 'Barcelona, Spain',
    distanceKm: 42.195,
    elevationGain: 195,
    elevationLoss: 190,
    difficulty: 1.05,
    surface: 'Road',
    description: 'Rolling course past Gaudí landmarks. Mid-race hill around montjuïc.',
    color: '#ED1C24',
    country: 'ES',
  },
  {
    id: 'dublin',
    name: 'Dublin Marathon',
    location: 'Dublin, Ireland',
    distanceKm: 42.195,
    elevationGain: 120,
    elevationLoss: 118,
    difficulty: 1.00,
    surface: 'Road',
    description: 'Mostly flat with a few gentle inclines. Known for incredible crowd support.',
    color: '#169B62',
    country: 'IE',
  },
  {
    id: 'marrakech',
    name: 'Marrakech Marathon',
    location: 'Marrakech, Morocco',
    distanceKm: 42.195,
    elevationGain: 52,
    elevationLoss: 50,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Flat course through palm groves and the Medina outskirts.',
    color: '#C1272D',
    country: 'MA',
  },
  {
    id: 'reykjavik',
    name: 'Reykjavik Marathon',
    location: 'Reykjavik, Iceland',
    distanceKm: 42.195,
    elevationGain: 75,
    elevationLoss: 72,
    difficulty: 0.95,
    surface: 'Road',
    description: 'Flat coastal course with ocean views and volcanic landscapes.',
    color: '#003897',
    country: 'IS',
  },
];

const halfMarathons = [
  {
    id: 'berlin-half',
    name: 'Berlin Half Marathon',
    location: 'Berlin, Germany',
    distanceKm: 21.0975,
    elevationGain: 38,
    elevationLoss: 36,
    difficulty: 0.95,
    surface: 'Road',
    description: 'Fast half through Berlin\'s iconic streets. Flat and scenic.',
    color: '#E3000F',
    country: 'DE',
  },
  {
    id: 'boston-half',
    name: 'Boston Half Marathon',
    location: 'Boston, USA',
    distanceKm: 21.0975,
    elevationGain: 118,
    elevationLoss: 142,
    difficulty: 1.10,
    surface: 'Road',
    description: 'Net downhill course. Features some rolling sections.',
    color: '#004B87',
    country: 'US',
  },
  {
    id: 'nyc-half',
    name: 'NYC Half Marathon',
    location: 'New York, USA',
    distanceKm: 21.0975,
    elevationGain: 152,
    elevationLoss: 148,
    difficulty: 1.12,
    surface: 'Road',
    description: 'Tour through Times Square and Central Park. Some hills.',
    color: '#FF6B35',
    country: 'US',
  },
  {
    id: 'lisbon-half',
    name: 'Lisbon Half Marathon',
    location: 'Lisbon, Portugal',
    distanceKm: 21.0975,
    elevationGain: 210,
    elevationLoss: 225,
    difficulty: 1.08,
    surface: 'Road',
    description: 'Net downhill course along the Tagus river. Very fast if legs hold up.',
    color: '#E32636',
    country: 'PT',
  },
  {
    id: 'prague-half',
    name: 'Prague Half Marathon',
    location: 'Prague, Czech Republic',
    distanceKm: 21.0975,
    elevationGain: 52,
    elevationLoss: 50,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Flat and fast along the Vltava River. Historic Old Town route.',
    color: '#E30A17',
    country: 'CZ',
  },
  {
    id: 'valencia-half',
    name: 'Valencia Half Marathon',
    location: 'Valencia, Spain',
    distanceKm: 21.0975,
    elevationGain: 18,
    elevationLoss: 16,
    difficulty: 0.87,
    surface: 'Road',
    description: 'Extremely flat. One of the fastest half marathon courses in Europe.',
    color: '#FFA500',
    country: 'ES',
  },
  {
    id: 'greek',
    name: 'Athens Marathon',
    location: 'Athens, Greece',
    distanceKm: 42.195,
    elevationGain: 315,
    elevationLoss: 115,
    difficulty: 1.30,
    surface: 'Road',
    description: 'Original marathon course from Marathon to Athens. Net uphill overall.',
    color: '#0D5EAF',
    country: 'GR',
  },
  {
    id: 'golden-gate-half',
    name: 'Golden Gate Half Marathon',
    location: 'San Francisco, USA',
    distanceKm: 21.0975,
    elevationGain: 245,
    elevationLoss: 248,
    difficulty: 1.25,
    surface: 'Road',
    description: 'Hilly course over the Golden Gate Bridge. Stunning but tough.',
    color: '#F5A623',
    country: 'US',
  },
];

const allCourses = [...marathons, ...halfMarathons];

export { marathons, halfMarathons, allCourses };
