const marathons = [
  {
    id: 'berlin',
    name: 'Berlin Marathon',
    location: 'Berlin, Germany',
    distanceKm: 42.195,
    elevationGain: 72,
    elevationLoss: 70,
    difficulty: 0.95,
    surface: 'Road',
    description: 'One of the fastest marathon courses in the world. Almost completely flat with wide streets.',
    color: '#E3000F',
    country: 'DE',
  },
  {
    id: 'boston',
    name: 'Boston Marathon',
    location: 'Boston, USA',
    distanceKm: 42.195,
    elevationGain: 243,
    elevationLoss: 294,
    difficulty: 1.15,
    surface: 'Road',
    description: 'Net downhill but features Heartbreak Hill at mile 20. Rolling hills throughout.',
    color: '#004B87',
    country: 'US',
  },
  {
    id: 'london',
    name: 'London Marathon',
    location: 'London, UK',
    distanceKm: 42.195,
    elevationGain: 115,
    elevationLoss: 118,
    difficulty: 1.00,
    surface: 'Road',
    description: 'Flat and fast course along the River Thames. Many iconic landmarks.',
    color: '#CF142B',
    country: 'GB',
  },
  {
    id: 'chicago',
    name: 'Chicago Marathon',
    location: 'Chicago, USA',
    distanceKm: 42.195,
    elevationGain: 56,
    elevationLoss: 53,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Very flat course through 29 neighborhoods. Excellent for fast times.',
    color: '#009CDE',
    country: 'US',
  },
  {
    id: 'nyc',
    name: 'NYC Marathon',
    location: 'New York, USA',
    distanceKm: 42.195,
    elevationGain: 312,
    elevationLoss: 315,
    difficulty: 1.20,
    surface: 'Road',
    description: 'Five-borough tour with multiple bridges. Verrazzano bridge start is iconic.',
    color: '#FF6B35',
    country: 'US',
  },
  {
    id: 'tokyo',
    name: 'Tokyo Marathon',
    location: 'Tokyo, Japan',
    distanceKm: 42.195,
    elevationGain: 48,
    elevationLoss: 45,
    difficulty: 0.92,
    surface: 'Road',
    description: 'Almost pancake flat. Excellent organization and crowd support.',
    color: '#BC002D',
    country: 'JP',
  },
  {
    id: 'bigsur',
    name: 'Big Sur Marathon',
    location: 'Big Sur, USA',
    distanceKm: 42.195,
    elevationGain: 430,
    elevationLoss: 415,
    difficulty: 1.35,
    surface: 'Road',
    description: 'Stunning coastal views but extremely challenging. Hurricane Point at mile 11.',
    color: '#2E8B57',
    country: 'US',
  },
  {
    id: 'paris',
    name: 'Paris Marathon',
    location: 'Paris, France',
    distanceKm: 42.195,
    elevationGain: 145,
    elevationLoss: 142,
    difficulty: 1.02,
    surface: 'Road',
    description: 'Mild rolling hills through the streets of Paris. Starts on Champs-Élysées.',
    color: '#002395',
    country: 'FR',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam Marathon',
    location: 'Amsterdam, Netherlands',
    distanceKm: 42.195,
    elevationGain: 38,
    elevationLoss: 36,
    difficulty: 0.90,
    surface: 'Road',
    description: 'Extremely flat course. Perfect for a personal best.',
    color: '#FF6600',
    country: 'NL',
  },
  {
    id: 'rome',
    name: 'Rome Marathon',
    location: 'Rome, Italy',
    distanceKm: 42.195,
    elevationGain: 180,
    elevationLoss: 178,
    difficulty: 1.08,
    surface: 'Road',
    description: 'Cobblestone sections and rolling hills. Historic landmarks throughout.',
    color: '#E32636',
    country: 'IT',
  },
  {
    id: 'valencia',
    name: 'Valencia Marathon',
    location: 'Valencia, Spain',
    distanceKm: 42.195,
    elevationGain: 30,
    elevationLoss: 28,
    difficulty: 0.88,
    surface: 'Road',
    description: 'Among the flattest marathons in the world. Top choice for record attempts.',
    color: '#FFA500',
    country: 'ES',
  },
  {
    id: 'prague',
    name: 'Prague Marathon',
    location: 'Prague, Czech Republic',
    distanceKm: 42.195,
    elevationGain: 95,
    elevationLoss: 92,
    difficulty: 0.97,
    surface: 'Road',
    description: 'Mostly flat with some cobblestone. Scenic route through Old Town.',
    color: '#E30A17',
    country: 'CZ',
  },
  {
    id: 'marina-bay',
    name: 'Marina Bay Marathon',
    location: 'Singapore',
    distanceKm: 42.195,
    elevationGain: 35,
    elevationLoss: 33,
    difficulty: 0.89,
    surface: 'Road',
    description: 'Flat coastal route. Warm and humid conditions add challenge.',
    color: '#EF2B2D',
    country: 'SG',
  },
  {
    id: 'vienna',
    name: 'Vienna Marathon',
    location: 'Vienna, Austria',
    distanceKm: 42.195,
    elevationGain: 68,
    elevationLoss: 65,
    difficulty: 0.94,
    surface: 'Road',
    description: 'Flat and fast through imperial Vienna. Ends at the Hofburg Palace.',
    color: '#C8102E',
    country: 'AT',
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen Marathon',
    location: 'Copenhagen, Denmark',
    distanceKm: 42.195,
    elevationGain: 42,
    elevationLoss: 40,
    difficulty: 0.91,
    surface: 'Road',
    description: 'Flat city course through the Danish capital. Great for beginners.',
    color: '#C60C30',
    country: 'DK',
  },
  {
    id: 'geneva',
    name: 'Geneva Marathon',
    location: 'Geneva, Switzerland',
    distanceKm: 42.195,
    elevationGain: 88,
    elevationLoss: 85,
    difficulty: 0.96,
    surface: 'Road',
    description: 'Flat lakeside course with views of Mont Blanc and Lake Geneva.',
    color: '#E32636',
    country: 'CH',
  },
  {
    id: 'barcelona',
    name: 'Barcelona Marathon',
    location: 'Barcelona, Spain',
    distanceKm: 42.195,
    elevationGain: 195,
    elevationLoss: 190,
    difficulty: 1.05,
    surface: 'Road',
    description: 'Rolling course past Gaudí landmarks. Mid-race hill around montjuïc.',
    color: '#ED1C24',
    country: 'ES',
  },
  {
    id: 'dublin',
    name: 'Dublin Marathon',
    location: 'Dublin, Ireland',
    distanceKm: 42.195,
    elevationGain: 120,
    elevationLoss: 118,
    difficulty: 1.00,
    surface: 'Road',
    description: 'Mostly flat with a few gentle inclines. Known for incredible crowd support.',
    color: '#169B62',
    country: 'IE',
  },
  {
    id: 'marrakech',
    name: 'Marrakech Marathon',
    location: 'Marrakech, Morocco',
    distanceKm: 42.195,
    elevationGain: 52,
    elevationLoss: 50,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Flat course through palm groves and the Medina outskirts.',
    color: '#C1272D',
    country: 'MA',
  },
  {
    id: 'reykjavik',
    name: 'Reykjavik Marathon',
    location: 'Reykjavik, Iceland',
    distanceKm: 42.195,
    elevationGain: 72,
    elevationLoss: 72,
    difficulty: 0.95,
    surface: 'Road',
    description: 'Flat coastal course with ocean views and volcanic landscapes.',
    color: '#003897',
    country: 'IS',
  },
  {
    id: 'greek',
    name: 'Athens Marathon',
    location: 'Athens, Greece',
    distanceKm: 42.195,
    elevationGain: 315,
    elevationLoss: 115,
    difficulty: 1.30,
    surface: 'Road',
    description: 'Original marathon course from Marathon to Athens. Net uphill overall.',
    color: '#0D5EAF',
    country: 'GR',
  },
  {
    id: 'rotterdam',
    name: 'Rotterdam Marathon',
    location: 'Rotterdam, Netherlands',
    distanceKm: 42.195,
    elevationGain: 25,
    elevationLoss: 23,
    difficulty: 0.87,
    surface: 'Road',
    description: 'Extremely flat and fast. One of the fastest marathon courses in Europe.',
    color: '#009B4C',
    country: 'NL',
  },
  {
    id: 'stockholm',
    name: 'Stockholm Marathon',
    location: 'Stockholm, Sweden',
    distanceKm: 42.195,
    elevationGain: 165,
    elevationLoss: 162,
    difficulty: 1.05,
    surface: 'Road',
    description: 'Two-loop course through Sweden\'s capital. Some rolling hills along Djurgården.',
    color: '#005B9F',
    country: 'SE',
  },
  {
    id: 'ottawa',
    name: 'Ottawa Marathon',
    location: 'Ottawa, Canada',
    distanceKm: 42.195,
    elevationGain: 88,
    elevationLoss: 85,
    difficulty: 0.95,
    surface: 'Road',
    description: 'Flat and fast course along the Rideau Canal and Ottawa River.',
    color: '#FF0000',
    country: 'CA',
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong Marathon',
    location: 'Hong Kong',
    distanceKm: 42.195,
    elevationGain: 380,
    elevationLoss: 375,
    difficulty: 1.40,
    surface: 'Road',
    description: 'Challenging course with tunnels and bridges. Humid conditions add difficulty.',
    color: '#EE2A7B',
    country: 'HK',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles Marathon',
    location: 'Los Angeles, USA',
    distanceKm: 42.195,
    elevationGain: 275,
    elevationLoss: 270,
    difficulty: 1.15,
    surface: 'Road',
    description: 'Stadium to the sea course with rolling hills through LA neighborhoods.',
    color: '#A5ACAF',
    country: 'US',
  },
  {
    id: 'munich',
    name: 'Munich Marathon',
    location: 'Munich, Germany',
    distanceKm: 42.195,
    elevationGain: 105,
    elevationLoss: 102,
    difficulty: 0.98,
    surface: 'Road',
    description: 'Flat course through Munich with Olympic Park finish.',
    color: '#008AD2',
    country: 'DE',
  },
  {
    id: 'budapest',
    name: 'Budapest Marathon',
    location: 'Budapest, Hungary',
    distanceKm: 42.195,
    elevationGain: 95,
    elevationLoss: 92,
    difficulty: 0.96,
    surface: 'Road',
    description: 'Flat course along both sides of the Danube. Views of Parliament and Buda Castle.',
    color: '#CE2939',
    country: 'HU',
  },
  {
    id: 'warsaw',
    name: 'Warsaw Marathon',
    location: 'Warsaw, Poland',
    distanceKm: 42.195,
    elevationGain: 55,
    elevationLoss: 52,
    difficulty: 0.92,
    surface: 'Road',
    description: 'Flat course through Warsaw\'s Old Town and along the Vistula River.',
    color: '#DC143C',
    country: 'PL',
  },
  {
    id: 'lisbon',
    name: 'Lisbon Marathon',
    location: 'Lisbon, Portugal',
    distanceKm: 42.195,
    elevationGain: 155,
    elevationLoss: 175,
    difficulty: 1.00,
    surface: 'Road',
    description: 'Net downhill along the Tagus River. Can be fast with tailwind.',
    color: '#E32636',
    country: 'PT',
  },
];

const halfMarathons = [
  {
    id: 'berlin-half',
    name: 'Berlin Half Marathon',
    location: 'Berlin, Germany',
    distanceKm: 21.0975,
    elevationGain: 38,
    elevationLoss: 36,
    difficulty: 0.95,
    surface: 'Road',
    description: 'Fast half through Berlin\'s iconic streets. Flat and scenic.',
    color: '#E3000F',
    country: 'DE',
  },
  {
    id: 'boston-half',
    name: 'Boston Half Marathon',
    location: 'Boston, USA',
    distanceKm: 21.0975,
    elevationGain: 118,
    elevationLoss: 142,
    difficulty: 1.10,
    surface: 'Road',
    description: 'Net downhill course. Features some rolling sections.',
    color: '#004B87',
    country: 'US',
  },
  {
    id: 'nyc-half',
    name: 'NYC Half Marathon',
    location: 'New York, USA',
    distanceKm: 21.0975,
    elevationGain: 152,
    elevationLoss: 148,
    difficulty: 1.12,
    surface: 'Road',
    description: 'Tour through Times Square and Central Park. Some hills.',
    color: '#FF6B35',
    country: 'US',
  },
  {
    id: 'lisbon-half',
    name: 'Lisbon Half Marathon',
    location: 'Lisbon, Portugal',
    distanceKm: 21.0975,
    elevationGain: 210,
    elevationLoss: 225,
    difficulty: 1.08,
    surface: 'Road',
    description: 'Net downhill course along the Tagus river. Very fast if legs hold up.',
    color: '#E32636',
    country: 'PT',
  },
  {
    id: 'prague-half',
    name: 'Prague Half Marathon',
    location: 'Prague, Czech Republic',
    distanceKm: 21.0975,
    elevationGain: 52,
    elevationLoss: 50,
    difficulty: 0.93,
    surface: 'Road',
    description: 'Flat and fast along the Vltava River. Historic Old Town route.',
    color: '#E30A17',
    country: 'CZ',
  },
  {
    id: 'valencia-half',
    name: 'Valencia Half Marathon',
    location: 'Valencia, Spain',
    distanceKm: 21.0975,
    elevationGain: 18,
    elevationLoss: 16,
    difficulty: 0.87,
    surface: 'Road',
    description: 'Extremely flat. One of the fastest half marathon courses in Europe.',
    color: '#FFA500',
    country: 'ES',
  },
  {
    id: 'golden-gate-half',
    name: 'Golden Gate Half Marathon',
    location: 'San Francisco, USA',
    distanceKm: 21.0975,
    elevationGain: 245,
    elevationLoss: 248,
    difficulty: 1.25,
    surface: 'Road',
    description: 'Hilly course over the Golden Gate Bridge. Stunning but tough.',
    color: '#F5A623',
    country: 'US',
  },
];

const ultraMarathons = [
  {
    id: 'comrades-down',
    name: 'Comrades Marathon (Down Run)',
    location: 'Pietermaritzburg → Durban, South Africa',
    distanceKm: 87.7,
    elevationGain: 760,
    elevationLoss: 1180,
    difficulty: 1.55,
    surface: 'Road',
    description: 'World\'s oldest ultramarathon. Net downhill from Pietermaritzburg to Durban, but features five major hills including the infamous Polly Shortts near the start.',
    color: '#228B22',
    country: 'ZA',
  },
  {
    id: 'comrades-up',
    name: 'Comrades Marathon (Up Run)',
    location: 'Durban → Pietermaritzburg, South Africa',
    distanceKm: 87.7,
    elevationGain: 1180,
    elevationLoss: 760,
    difficulty: 1.65,
    surface: 'Road',
    description: 'The tougher direction. Net uphill from Durban to Pietermaritzburg with relentless climbing in the second half.',
    color: '#006400',
    country: 'ZA',
  },
  {
    id: 'two-oceans',
    name: 'Two Oceans Ultra Marathon',
    location: 'Cape Town, South Africa',
    distanceKm: 56,
    elevationGain: 760,
    elevationLoss: 760,
    difficulty: 1.45,
    surface: 'Road',
    description: 'Scenic 56km along the Cape Peninsula. Known as the "world\'s most beautiful marathon" with Chapman\'s Peak at the halfway mark.',
    color: '#1E90FF',
    country: 'ZA',
  },
  {
    id: 'ccc',
    name: 'CCC (Courmayeur-Champex-Chamonix)',
    location: 'Italy/Switzerland/France',
    distanceKm: 101,
    elevationGain: 6150,
    elevationLoss: 6150,
    difficulty: 2.50,
    surface: 'Trail',
    description: 'Circuito dei tre Comuni — 101km through the Alps around Mont Blanc. Massive vert but stunning glacier views.',
    color: '#8B0000',
    country: 'FR',
  },
  {
    id: 'utmb',
    name: 'UTMB (Ultra-Trail du Mont-Blanc)',
    location: 'Chamonix, France',
    distanceKm: 171,
    elevationGain: 10000,
    elevationLoss: 10000,
    difficulty: 3.00,
    surface: 'Trail',
    description: 'The pinnacle of trail ultra running. 171km around Mont Blanc through France, Italy, and Switzerland with 10,000m of climbing.',
    color: '#2F4F4F',
    country: 'FR',
  },
  {
    id: 'western-states',
    name: 'Western States 100',
    location: 'Olympic Valley → Auburn, USA',
    distanceKm: 161,
    elevationGain: 5500,
    elevationLoss: 7000,
    difficulty: 2.80,
    surface: 'Trail',
    description: 'The world\'s oldest 100-mile trail race. Net downhill from Squaw Valley to Auburn through canyons and forests.',
    color: '#D2691E',
    country: 'US',
  },
  {
    id: 'leadville',
    name: 'Leadville 100',
    location: 'Leadville, Colorado, USA',
    distanceKm: 161,
    elevationGain: 4800,
    elevationLoss: 4800,
    difficulty: 3.20,
    surface: 'Trail',
    description: 'The Race Across the Sky. Runs at 10,000–12,600ft altitude. Extreme thin air makes this one of the toughest.',
    color: '#4A0E4E',
    country: 'US',
  },
  {
    id: 'tarawera',
    name: 'Tarawera Ultra',
    location: 'Rotorua, New Zealand',
    distanceKm: 102,
    elevationGain: 2100,
    elevationLoss: 2100,
    difficulty: 2.10,
    surface: 'Trail',
    description: 'Point-to-point trail through NZ volcanic terrain. Redwood forests, lakes, and geothermal valleys.',
    color: '#2E8B57',
    country: 'NZ',
  },
  {
    id: 'marathon-des-sables',
    name: 'Marathon des Sables',
    location: 'Sahara Desert, Morocco',
    distanceKm: 250,
    elevationGain: 1200,
    elevationLoss: 1200,
    difficulty: 4.50,
    surface: 'Sand',
    description: 'The toughest footrace on Earth. 250km self-supported across the Sahara in 6 stages. Sand dunes, heat, and blisters.',
    color: '#C8A951',
    country: 'MA',
  },
];

const allCourses = [...marathons, ...halfMarathons, ...ultraMarathons];

export { marathons, halfMarathons, allCourses };
